spring: 
  application:
    name: graphql-courses
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        "[format_sql]": true
  graphql:
    graphiql:
      enabled: true
  flyway:
    baseline-on-migrate: true
    enabled: true